name: kawaii
version: 0.0.1.0
synopsis: Utilities for serving static sites and blogs with Wai/Warp
maintainer: Eduardo Trujillo <ed@chromabits.com>
license: Apache
github: etcinit/kawaii
category: Web

ghc-options: -threaded -rtsopts -with-rtsopts=-N -Wall -Werror

default-extensions:
  - LambdaCase

dependencies:
  - base >= 4.7 && < 5
  - safe == 0.3.*
  - text
  - lens
  - bytestring
  - hakyll
  - optparse-applicative
  - warp == 3.*
  - warp-tls == 3.*
  - wai == 3.*
  - wai-extra >= 3.0.14
  - wai-app-static == 3.*
  - streaming-commons == 0.1.*
  - containers
  - data-default
  - lifted-base
  - mtl
  - monad-logger
  - monad-control

library:
  source-dirs: src

tests:
  wai-static-extra-spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hakyll-serve
      - hspec
      - QuickCheck
